services:
  workspace-service:
    build:
      context: ./services/workspace-service
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    networks:
      - microservices
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:8081/actuator/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

  booking-service:
    build:
      context: ./services/booking-service
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    networks:
      - microservices
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:8082/actuator/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

  payment-service:
    build:
      context: ./services/payment-service
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    networks:
      - microservices
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:8083/actuator/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

networks:
  microservices:
    driver: bridge



# # 1. Задать GID docker-сокета (нужно из‑за jenkins/jenkins-agent)
# export DOCKER_GID=$(stat -c %g /var/run/docker.sock)

# # 2. Поднять только инфраструктуру
# DOCKER_GID=$DOCKER_GID docker compose -f docker-compose.infra.yml up -d --build

# docker compose -f docker-compose.infra.yml ps

# export DOCKER_GID=$(stat -c %g /var/run/docker.sock)
# docker compose -f docker-compose.infra.yml build jenkins --no-cache
# docker compose -f docker-compose.infra.yml up -d --force-recreate jenkins
# docker compose -f docker-compose.infra.yml exec jenkins git config --system --get-all safe.directory